#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Postcode\PostcodeCommand;

$app = new Application();
$app->add($postcodeCommand = new PostcodeCommand());
$app->setDefaultCommand($postcodeCommand->getName(), true);
$app->run();

?>
